## Converting from Remo Format to Pascal VOC format

In [ ]:
cd ..

/


In [ ]:
import json
import xml.etree.ElementTree as ET

In [ ]:
def data_to_xml(image_width, image_height, image_filename, boxes, classes):
    annotation = ET.Element('annotation')

    filename = ET.SubElement(annotation, 'filename')
    filename.text = image_filename


    size = ET.SubElement(annotation, 'size')

    width = ET.SubElement(size, 'width')
    width.text = image_width
    height = ET.SubElement(size, 'height')
    height.text = image_height
    depth = ET.SubElement(size, 'depth')
    depth.text = '3'

    for i in range(len(classes)):

        object = ET.SubElement(annotation, 'object')

        name = ET.SubElement(object, 'name')
        name.text = classes[i].lower()

        pose = ET.SubElement(object, 'pose')
        pose.text = "Unspecified"
        
        truncated = ET.SubElement(object, 'truncated')
        truncated.text = "0"

        difficult = ET.SubElement(object, 'difficult')
        difficult.text = "0"

        bndbox = ET.SubElement(object, 'bndbox')

        xmin = ET.SubElement(bndbox, 'xmin')
        xmin.text = boxes[i][0]
        ymin = ET.SubElement(bndbox, 'ymin')
        ymin.text = boxes[i][1]
        xmax = ET.SubElement(bndbox, 'xmax')
        xmax.text = boxes[i][2]
        ymax = ET.SubElement(bndbox, 'ymax')
        ymax.text = boxes[i][3]




    b_xml = ET.tostring(annotation)

    image_filename = image_filename[:-4]
    with open("annotations/" + image_filename + ".xml", "wb") as f:
        f.write(b_xml)
    return None

In [ ]:
with open('/content/Fashion_Dataset_Annotations.json') as f:
    data = json.load(f)

for i in range(len(data)):

    image_width = str(data[i]["width"])
    image_height = str(data[i]["height"])
    image_filename = str(data[i]["file_name"])

    boxes = []
    classes = []
    for j in range(len(data[i]['annotations'])):
        boxes.append([str(data[i]['annotations'][j]["bbox"]['xmin']), str(data[i]['annotations'][j]["bbox"]['ymin']), 
                      str(data[i]['annotations'][j]["bbox"]['xmax']), str(data[i]['annotations'][j]["bbox"]['ymax'])])
        
        try:
            classes.append(data[i]['annotations'][j]["classes"][0])
        except:
            print("Error")


    data_to_xml(image_width, image_height, image_filename, boxes, classes)

FileNotFoundError: ignored

In [ ]:
!cp annotations/new_data_10.xml /content/YOLOX/datasets/VOCdevkit/VOC2007/Annotations

cp: cannot stat 'annotations/new_data_10.xml': No such file or directory


# Installation

In [ ]:
!git clone https://github.com/Megvii-BaseDetection/YOLOX/

Cloning into 'YOLOX'...
remote: Enumerating objects: 1665, done.
remote: Total 1665 (delta 0), reused 0 (delta 0), pack-reused 1665
Receiving objects: 100% (1665/1665), 6.02 MiB | 3.76 MiB/s, done.
Resolving deltas: 100% (977/977), done.


In [ ]:
cd YOLOX

/content/YOLOX


In [ ]:
!pip3 install -U pip && pip3 install -r requirements.txt
!pip3 install -v -e .  # or  python3 setup.py develop
!pip3 install wandb

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.1 MB 4.8 MB/s 
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.1/108.1 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.5/14.5 MB 73.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 97.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.6/498.6 kB 42.7 MB/s eta 0:00:00
  Created wheel for onnx-simplifier: filename=onnx_simplifier-0.3.5-py3-none-any.whl size=12878 sha256=3a75acdcb3cf9f680fc7a279d763b85e8063708166d44a6ba65d0a5d

# Demo

## Yolox-x Demo

In [ ]:
!wget https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_x.pth

--2022-06-03 23:06:30--  https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_x.pth
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/386811486/41678999-3e97-4a8e-8a2a-f45da504a583?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220603%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220603T230630Z&X-Amz-Expires=300&X-Amz-Signature=44f20013aa7c005224220a9642af8b084baaa5b9d80eb49dfc964faff4e99db2&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=386811486&response-content-disposition=attachment%3B%20filename%3Dyolox_x.pth&response-content-type=application%2Foctet-stream [following]
--2022-06-03 23:06:31--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/386811486/41678999-3e97-4a8e-8a2a-f45da504a583?

In [ ]:
!python tools/demo.py image -n yolox-x -c weights/yolox_x.pth --path assets/new_data_1.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result --device gpu

2022-06-03 23:07:51.109 | INFO     | __main__:main:259 - Args: Namespace(camid=0, ckpt='weights/yolox_x.pth', conf=0.3, demo='image', device='gpu', exp_file=None, experiment_name='yolox_x', fp16=False, fuse=False, legacy=False, name='yolox-x', nms=0.65, path='assets/new_data_1.jpg', save_result=True, trt=False, tsize=640)
2022-06-03 23:07:52.484 | INFO     | __main__:main:269 - Model Summary: Params: 99.07M, Gflops: 281.93
2022-06-03 23:08:02.930 | INFO     | __main__:main:282 - loading checkpoint
Traceback (most recent call last):
  File "tools/demo.py", line 320, in <module>
    main(exp, args)
  File "tools/demo.py", line 283, in main
    ckpt = torch.load(ckpt_file, map_location="cpu")
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/loc

## Yolox-s Demo

In [ ]:
!wget https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth

--2022-06-03 23:08:03--  https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/386811486/42c4cb47-f94e-475b-a3a2-57f31f26fa5d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220603%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220603T230803Z&X-Amz-Expires=300&X-Amz-Signature=d95337cd6b09789af8bd57824f2f59083e648c8352c03a1aa6c42639bee0c8b2&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=386811486&response-content-disposition=attachment%3B%20filename%3Dyolox_s.pth&response-content-type=application%2Foctet-stream [following]
--2022-06-03 23:08:03--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/386811486/42c4cb47-f94e-475b-a3a2-57f31f26fa5d?

In [ ]:
!python tools/demo.py image -f exps/default/yolox_s -c weights/best_ckpt_yolox_s.pth --path assets/new_data_6.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result --device gpu

2022-06-03 23:08:10.882 | INFO     | __main__:main:259 - Args: Namespace(camid=0, ckpt='weights/best_ckpt_yolox_s.pth', conf=0.3, demo='image', device='gpu', exp_file='exps/default/yolox_s', experiment_name='yolox_s', fp16=False, fuse=False, legacy=False, name=None, nms=0.65, path='assets/new_data_6.jpg', save_result=True, trt=False, tsize=640)
2022-06-03 23:08:11.111 | INFO     | __main__:main:269 - Model Summary: Params: 8.97M, Gflops: 26.81
2022-06-03 23:08:14.818 | INFO     | __main__:main:282 - loading checkpoint
Traceback (most recent call last):
  File "tools/demo.py", line 320, in <module>
    main(exp, args)
  File "tools/demo.py", line 283, in main
    ckpt = torch.load(ckpt_file, map_location="cpu")
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, m

## Yolox-nano Demo

In [ ]:
!wget https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_nano.pth

In [ ]:
!python tools/demo.py image -n yolox-nano -c weights/best_yolox_nano.pth --path assets/new_data_10.jpg --conf 0.2 --nms 0.65 --tsize 416 --save_result --device gpu

# Training and Evaluation

## Copy Dataset

In [ ]:
!cp /content/drive/MyDrive/colorful_fashion_dataset_for_object_detection.rar /content/YOLOX/datasets/

In [ ]:
!unrar x "/content/YOLOX/datasets/colorful_fashion_dataset_for_object_detection.rar" "/content/YOLOX/datasets/fashion/"

## Training

### Training Yolox-s

In [ ]:
!python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 16 --fp16 -o -c weights/yolox_s.pth

In [ ]:
!cp /content/YOLOX/YOLOX_outputs/yolox_voc_s/best_ckpt.pth /content/YOLOX/weights

### Training Yolox-nano with Wandb integration

In [ ]:
import wandb

In [ ]:
!wandb login

In [ ]:
!python tools/train.py -f exps/example/yolox_voc/yolox_voc_nano.py -d 1 -b 16 --fp16 -o --logger wandb wandb-project object-detection -c weights/yolox_nano.pth

In [ ]:
!python tools/train.py -f exps/example/yolox_voc/yolox_voc_nano.py -d 1 -b 16 --fp16 -o -c weights/yolox_nano.pth

## Evaluation

In [ ]:
!python -m yolox.tools.eval -f exps/example/yolox_voc/yolox_voc_nano.py -c /content/YOLOX/YOLOX_outputs/yolox_voc_nano/best_ckpt.pth -b 64 -d 1 --conf 0.1 --fp16

# Conversion to ONNX

In [ ]:
# !python3 tools/export_onnx.py -f exps/example/yolox_voc/yolox_voc_nano.py --output-name weights/best_yolox_nano.onnx -c weights/best_yolox_nano.pth

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!mkdir weights

In [ ]:
! cp '/content/drive/My Drive/Deep_Learning/demo.jpg' assets
! cp '/content/drive/My Drive/Deep_Learning/best_yolox_nano.onnx'  weights

In [ ]:
# !python3 demo/ONNXRuntime/onnx_inference.py -m weights/best_yolox_nano.onnx -i assets/demo.jpg -o demo -s 0.3 --input_shape 416,416

In [ ]:
!cp '/content/drive/My Drive/onnx_inference_modified.py' demo/ONNXRuntime/

In [ ]:
!python3 demo/ONNXRuntime/onnx_inference_modified.py -m weights/best_yolox_nano.onnx -i assets/demo.jpg -o demo -s 0.3 --input_shape 416,416

[[8.0108643e-05]
 [7.1585178e-05]
 [1.9341707e-05]
 ...
 [3.3825636e-05]
 [1.5169382e-05]
 [2.1755695e-06]]
demo/demo.jpg


In [ ]:
!ls demo

boxes.npy  MegEngine  ONNXRuntime  output_net.npy   scores.npy
demo.jpg   ncnn       OpenVINO	   predictions.npy  TensorRT


In [ ]:
!cp demo/demo.jpg '/content/drive/My Drive/'

In [ ]:
!cp demo/preprocessed_img1.jpg '/content/drive/My Drive'

In [ ]:
!cp demo/boxes.npy '/content/drive/My Drive'
!cp demo/predictions.npy '/content/drive/My Drive'
!cp demo/scores.npy '/content/drive/My Drive'
!cp demo/output_net.npy '/content/drive/My Drive'

In [ ]:
def demo_postprocess(img_size, p6=False):
    import numpy as np
    grids = []
    expanded_strides = []

    if not p6:
        strides = [8, 16, 32]
    else:
        strides = [8, 16, 32, 64]

    hsizes = [img_size[0] // stride for stride in strides]
    wsizes = [img_size[1] // stride for stride in strides]

    for hsize, wsize, stride in zip(hsizes, wsizes, strides):
        xv, yv = np.meshgrid(np.arange(wsize), np.arange(hsize))
        grid = np.stack((xv, yv), 2).reshape(1, -1, 2)
        grids.append(grid)
        shape = grid.shape[:2]
        expanded_strides.append(np.full((*shape, 1), stride))

    grids = np.concatenate(grids, 1)
    expanded_strides = np.concatenate(expanded_strides, 1)
    print(len(expanded_strides[0]))

In [ ]:
demo_postprocess((540, 680))

7417


In [ ]:
import numpy as np
a, b = np.meshgrid(np.arange(5), np.arange(6))

In [ ]:
print(a)
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
