In [ ]:
from PIL import Image
import cv2
import numpy as np
import pandas as pd 
import tensorflow as tf

In [ ]:
#!pip install paddlepaddle-gpu==2.3.2 cudatoolkit==10.2

In [ ]:
!pip install paddlepaddle-gpu==2.3.0.post110 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
     |████████████████████████████████| 532.9 MB 27 kB/s 
     |████████████████████████████████| 373 kB 5.7 MB/s 


# pdf2image

## Installation

In [ ]:
!pip install pdf2image
!apt-get update
!apt-get install poppler-utils

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:6 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Hit:12 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:13 h

## Conversion

In [ ]:
from pdf2image import convert_from_path

In [ ]:
images = convert_from_path('/content/bahdanau attention.pdf')

In [ ]:
!mkdir pages

In [ ]:
for i in range(len(images)):
  images[i].save('pages/page'+str(i)+'.jpg', 'JPEG')

# Layout

## Installation

In [ ]:
#!python3 -m pip install paddlepaddle-gpu
!pip install "paddleocr>=2.0.1"
!pip install protobuf==3.20.0
!git clone https://github.com/PaddlePaddle/PaddleOCR.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 409 kB 6.1 MB/s 
     |████████████████████████████████| 5.6 MB 56.9 MB/s 
     |████████████████████████████████| 8.7 MB 19.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 604 kB 62.9 MB/s 
     |████████████████████████████████| 87 kB 7.9 MB/s 
     |████████████████████████████████| 2.2 MB 52.5 MB/s 
     |████████████████████████████████| 148 kB 68.2 MB/s 
     |████████████████████████████████| 4.9 MB 46.1 MB/s 
     |████████████████████████████████| 965 kB 57.7 MB/s 
     |████████████████████████████████| 399 kB 56.6 MB/s 
     |████████████████████████████████| 115 kB 70.8 MB/s 
     |████████████████████████████████| 204 kB 74.4 MB/s 
     |████████████████████████████████| 2.3 MB 52.8 MB/s 
  Created wheel for lanm

Cloning into 'PaddleOCR'...
remote: Enumerating objects: 44967, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 44967 (delta 43), reused 45 (delta 23), pack-reused 44869
Receiving objects: 100% (44967/44967), 338.24 MiB | 33.36 MiB/s, done.
Resolving deltas: 100% (31741/31741), done.


In [ ]:
a=5

In [ ]:
!wget https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
!pip install -U layoutparser-0.0.0-py3-none-any.whl

--2022-11-18 12:58:08--  https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
Resolving paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)... 103.235.46.61, 2409:8c04:1001:1002:0:ff:b001:368a
Connecting to paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)|103.235.46.61|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19145360 (18M) [application/octet-stream]
Saving to: ‘layoutparser-0.0.0-py3-none-any.whl’

layoutparser-0.0.0- 100%[===================>]  18.26M  3.69MB/s    in 12s     

2022-11-18 12:58:23 (1.48 MB/s) - ‘layoutparser-0.0.0-py3-none-any.whl’ saved [19145360/19145360]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./layoutparser-0.0.0-py3-none-any.whl
     |████████████████████████████████| 42 kB 38 kB/s 
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31548 sha256=8f3da2a0ce4dd2c6b432ef4d5851d960b4c889e015e7066a5a77b45bfa05cb60
  Stored in 

## Table Extraction

In [ ]:
import cv2
import layoutparser as lp
image = cv2.imread("/content/pages/page13.jpg")

image = image[..., ::-1]

# load model
model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
                                threshold=0.5,
                                label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"},
                                enforce_cpu=False,
                                enable_mkldnn=True)#math kernel library
# detect
layout = model.detect(image)

download https://paddle-model-ecology.bj.bcebos.com/model/layout-parser/ppyolov2_r50vd_dcn_365e_publaynet.tar to /root/.paddledet/inference_model/ppyolov2_r50vd_dcn_365e_publaynet/ppyolov2_r50vd_dcn_365e_publaynet_infer/ppyolov2_r50vd_dcn_365e_publaynet.tar


100%|██████████| 221M/221M [00:37<00:00, 5.92MiB/s]


In [ ]:
layout

Layout(_blocks=[TextBlock(block=Rectangle(x_1=300.35406494140625, y_1=1716.4278564453125, x_2=1401.105712890625, y_2=1876.4561767578125), text=None, id=None, type=Text, parent=None, next=None, score=0.947794497013092), TextBlock(block=Rectangle(x_1=296.242431640625, y_1=1969.3675537109375, x_2=1405.8653564453125, y_2=2034.4422607421875), text=None, id=None, type=Text, parent=None, next=None, score=0.934190034866333), TextBlock(block=Rectangle(x_1=296.2332763671875, y_1=1460.10986328125, x_2=1401.1175537109375, y_2=1553.036865234375), text=None, id=None, type=Text, parent=None, next=None, score=0.924132227897644), TextBlock(block=Rectangle(x_1=294.98626708984375, y_1=444.1419677734375, x_2=1408.130126953125, y_2=567.1005249023438), text=None, id=None, type=Text, parent=None, next=None, score=0.9196642637252808), TextBlock(block=Rectangle(x_1=300.4600830078125, y_1=1669.076171875, x_2=711.9566040039062, y_2=1697.28076171875), text=None, id=None, type=Title, parent=None, next=None, score=

In [ ]:
x_1=0
y_1=0
x_2=0
y_2=0

for l in layout:
  #print(l)
  if l.type == 'Table':
    x_1 = int(l.block.x_1)
    print(l.block.x_1)
    y_1 = int(l.block.y_1)
    x_2 = int(l.block.x_2)
    y_2 = int(l.block.y_2)
    
    break

297.86298


In [ ]:
print(x_1,y_1,x_2,y_2)

297 220 1409 418


In [ ]:
im = cv2.imread('/content/pages/page13.jpg')

In [ ]:
cv2.imwrite('ext_im.jpg', im[y_1:y_2,x_1:x_2])

True

# Text Detection and Recognition

In [ ]:
from paddleocr import PaddleOCR, draw_ocr

In [ ]:
ocr = PaddleOCR(lang='en')
image_path = '/content/ext_im.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)[0]

download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to /root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer/en_PP-OCRv3_det_infer.tar


100%|██████████| 4.00M/4.00M [00:07<00:00, 505kiB/s] 


download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar to /root/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer/en_PP-OCRv3_rec_infer.tar


100%|██████████| 9.96M/9.96M [00:14<00:00, 693kiB/s] 


download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to /root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar


100%|██████████| 2.19M/2.19M [00:11<00:00, 190kiB/s]

[2022/11/18 13:00:00] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set

[2022/11/18 13:00:00] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2022/11/18 13:00:01] ppocr DEBUG: dt_boxes num : 42, elapse : 0.12288975715637207
[2022/11/18 13:00:01] ppocr DEBUG: rec_res num  : 42, elapse : 0.12553930282592773


In [ ]:
print(output)

[[[[693.0, 4.0], [755.0, 4.0], [755.0, 36.0], [693.0, 36.0]], ('GPU', 0.9990124106407166)], [[[70.0, 5.0], [148.0, 5.0], [148.0, 36.0], [70.0, 36.0]], ('Model', 0.9997721910476685)], [[[230.0, 5.0], [394.0, 8.0], [394.0, 37.0], [229.0, 35.0]], ('Updates (105)', 0.9652137756347656)], [[[425.0, 5.0], [511.0, 5.0], [511.0, 36.0], [425.0, 36.0]], ('Epochs', 0.9998965263366699)], [[[537.0, 5.0], [612.0, 5.0], [612.0, 36.0], [537.0, 36.0]], ('Hours', 0.9620624780654907)], [[[833.0, 4.0], [958.0, 4.0], [958.0, 33.0], [833.0, 33.0]], ('Train NLL', 0.9994094371795654)], [[[988.0, 6.0], [1104.0, 6.0], [1104.0, 32.0], [988.0, 32.0]], ('Dev.NLL', 0.9872051477432251)], [[[42.0, 47.0], [177.0, 47.0], [177.0, 72.0], [42.0, 72.0]], ('RNNenc-30', 0.9995856881141663)], [[[285.0, 46.0], [341.0, 46.0], [341.0, 74.0], [285.0, 74.0]], ('8.46', 0.9999933242797852)], [[[446.0, 46.0], [489.0, 46.0], [489.0, 74.0], [446.0, 74.0]], ('6.4', 0.9964627623558044)], [[[553.0, 45.0], [599.0, 45.0], [599.0, 74.0], [553

In [ ]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [ ]:
image_boxes = image_cv.copy()


In [ ]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [ ]:
cv2.imwrite('detections.jpg', image_boxes)

True

# Reconstruction

## Get Horizontal and Vertical Lines

In [ ]:
im = image_cv.copy()

In [ ]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)
  

In [ ]:
cv2.imwrite('horiz_vert.jpg',im)

True

## Non-Max Suppression

In [ ]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 3  8 20 24 34 36]


In [ ]:
im_nms = image_cv.copy()

In [ ]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)
  

In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [ ]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
print(vert_out)

tf.Tensor([ 8 10 34 12  3  1 39], shape=(7,), dtype=int32)


In [ ]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[ 1  3  8 10 12 34 39]


In [ ]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)
  

In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

## Convert to CSV

In [ ]:


out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(6, 7)
[['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', ''], ['', '', '', '', '', '', '']]


In [ ]:

unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[70, 0, 148, 198]
[425, 0, 511, 198]
[285, 0, 341, 198]
[553, 0, 599, 198]
[869, 0, 923, 198]
[1018, 0, 1075, 198]
[644, 0, 804, 198]


In [ ]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[0 2 1 3 6 4 5]


In [ ]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [ ]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0
      
  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))
  
  return inter / float(box_1_area + box_2_area - inter)

In [ ]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [ ]:
out_array=np.array(out_array)

In [ ]:
out_array

array([['Model', 'Updates (105)', 'Epochs', 'Hours', 'GPU', 'Train NLL',
        'Dev.NLL'],
       ['RNNenc-30', '8.46', '6.4', '109', 'TITAN BLACK', '28.1', '53.0'],
       ['RNNenc-50', '6.00', '4.5', '108', 'Quadro K-6000', '44.0',
        '43.6'],
       ['RNNsearch-30', '4.71', '3.6', '113', 'TITAN BLACK', '26.7',
        '47.2'],
       ['RNNsearch-50', '2.88', '2.2', '111', 'Quadro K-6000', '40.7',
        '38.1'],
       ['RNNsearch-50*', '6.67', '5.0', '252', 'Quadro K-6000', '36.7',
        '35.2']], dtype='<U13')

In [ ]:
pd.DataFrame(out_array).to_csv('sample.csv')

## Merging Cells

In [ ]:
current_bank=['']*len(out_array[0,:])
print(current_bank)

['', '', '', '', '', '', '']


In [ ]:
def empty(arr):
  for i in arr:
    if i=='':
      return True
  return False

In [ ]:
cleaned_array=[]

In [ ]:
for i in range(len(out_array)):
  if not empty(out_array[i]):
    current_bank=[out_array[i][j] for j in range(len(out_array[i]))]
    cleaned_array.append(current_bank)
    not_empty=True
  else:
    for j in range(len(out_array[i])):
      current_bank[j]+=' '+out_array[i][j]
    print('-->',current_bank)
cleaned_array=np.array(cleaned_array)
print(cleaned_array)

[['Model' 'Updates (105)' 'Epochs' 'Hours' 'GPU' 'Train NLL' 'Dev.NLL']
 ['RNNenc-30' '8.46' '6.4' '109' 'TITAN BLACK' '28.1' '53.0']
 ['RNNenc-50' '6.00' '4.5' '108' 'Quadro K-6000' '44.0' '43.6']
 ['RNNsearch-30' '4.71' '3.6' '113' 'TITAN BLACK' '26.7' '47.2']
 ['RNNsearch-50' '2.88' '2.2' '111' 'Quadro K-6000' '40.7' '38.1']
 ['RNNsearch-50*' '6.67' '5.0' '252' 'Quadro K-6000' '36.7' '35.2']]


In [ ]:
pd.DataFrame(cleaned_array).to_csv('cleaned.csv')

# Convert to OWL Format

# **CSV to Text**

In [ ]:
import  jpype     
import  asposecells  


jpype.startJVM() 
from asposecells.api import Workbook

workbook = Workbook("/content/sample.csv")
workbook.save("Output.docx")
jpype.shutdownJVM()

ModuleNotFoundError: ignored

# Brighten Image (For Anyone dealing with PDFs created from scanned images)

In [ ]:
from PIL import Image, ImageEnhance

#read the image
im = Image.open("ext_im.jpg")

#image brightness enhancer
enhancer = ImageEnhance.Brightness(im)

factor = 1 #gives original image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-1.jpg')

factor = 1.5## brightens the image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-2.jpg')
